AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Relax metrics for test files
Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  Exclude:
    - "test/**/*"

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "*.gemspec"
