# frozen_string_literal: true

require_relative "integration_helper"

class AttachmentTest < Minitest::Test
  # Sample attachment HTML as generated by ActionText
  # In production, this would have a real SGID and content-type
  SAMPLE_ATTACHMENT = <<~HTML.strip
    <action-text-attachment sgid="BAh7CEkiCG" content-type="image/png" filename="test.png"></action-text-attachment>
  HTML

  SAMPLE_CONTENT_WITH_ATTACHMENT = <<~HTML.strip
    <div class="trix-content">
      <p>Here is an image:</p>
      <action-text-attachment sgid="BAh7CEkiCG" content-type="image/png" filename="test.png"></action-text-attachment>
      <p>And some text after.</p>
    </div>
  HTML

  SAMPLE_GALLERY = <<~HTML.strip
    <div class="trix-content">
      <action-text-attachment sgid="BAh7CEkiCG1" content-type="image/png" filename="img1.png" presentation="gallery"></action-text-attachment>
      <action-text-attachment sgid="BAh7CEkiCG2" content-type="image/png" filename="img2.png" presentation="gallery"></action-text-attachment>
    </div>
  HTML

  def setup
    Article.delete_all
    Mobility::Backends::ActiveRecord::KeyValue::TextTranslation.delete_all
  end

  # Attachment Tag Preservation Tests

  def test_attachment_tags_preserved_in_content
    content = Mobility::RichText::Content.new(SAMPLE_ATTACHMENT)

    assert_includes content.to_html, "<action-text-attachment"
    assert_includes content.to_html, 'sgid="BAh7CEkiCG"'
    assert_includes content.to_html, 'content-type="image/png"'
    assert_includes content.to_html, 'filename="test.png"'
  end

  def test_attachment_tags_preserved_through_backend_round_trip
    article = Article.create!
    article.content = SAMPLE_CONTENT_WITH_ATTACHMENT
    article.save!

    article.reload

    assert_includes article.content.to_html, "<action-text-attachment"
    assert_includes article.content.to_html, 'sgid="BAh7CEkiCG"'
  end

  def test_mixed_content_preserved
    article = Article.create!
    article.content = SAMPLE_CONTENT_WITH_ATTACHMENT
    article.save!

    article.reload

    html = article.content.to_html
    assert_includes html, "Here is an image:"
    assert_includes html, "<action-text-attachment"
    assert_includes html, "And some text after."
  end

  def test_multiple_attachments_preserved
    article = Article.create!
    article.content = SAMPLE_GALLERY
    article.save!

    article.reload

    html = article.content.to_html
    assert_includes html, 'sgid="BAh7CEkiCG1"'
    assert_includes html, 'sgid="BAh7CEkiCG2"'
  end

  # Content Class Attachment Method Tests

  def test_content_responds_to_attachments
    content = Mobility::RichText::Content.new(SAMPLE_ATTACHMENT)

    # The content reader provides access to ActionText::Content
    assert_respond_to content.content, :attachments
  end

  def test_content_responds_to_gallery_attachments
    content = Mobility::RichText::Content.new(SAMPLE_GALLERY)

    assert_respond_to content.content, :gallery_attachments
  end

  def test_content_responds_to_links
    content = Mobility::RichText::Content.new('<a href="https://example.com">Link</a>')

    assert_respond_to content.content, :links
  end

  def test_links_extraction_works
    html = '<p>Visit <a href="https://example.com">example</a> and <a href="https://test.com">test</a></p>'
    content = Mobility::RichText::Content.new(html)

    links = content.content.links
    assert_includes links, "https://example.com"
    assert_includes links, "https://test.com"
  end

  # Plain Text Extraction Tests

  def test_plain_text_works_without_attachments
    # to_plain_text with attachment tags requires GlobalID to resolve
    # SGIDs, which isn't available in our standalone test environment.
    content = Mobility::RichText::Content.new("<p>Hello <strong>world</strong></p>")

    plain_text = content.to_plain_text
    assert_equal "Hello world", plain_text
  end

  # Multiple Locales with Attachments

  def test_attachments_work_across_locales # rubocop:disable Metrics/AbcSize
    article = Article.create!

    Mobility.with_locale(:en) do
      article.content = '<p>English with <action-text-attachment sgid="EN123"></action-text-attachment></p>'
    end

    Mobility.with_locale(:es) do
      article.content = '<p>Spanish with <action-text-attachment sgid="ES456"></action-text-attachment></p>'
    end

    article.save!
    article.reload

    Mobility.with_locale(:en) do
      assert_includes article.content.to_html, 'sgid="EN123"'
      refute_includes article.content.to_html, 'sgid="ES456"'
    end

    Mobility.with_locale(:es) do
      assert_includes article.content.to_html, 'sgid="ES456"'
      refute_includes article.content.to_html, 'sgid="EN123"'
    end
  end

  # Edge Cases

  def test_empty_attachment_tag_handled
    html = "<action-text-attachment></action-text-attachment>"
    content = Mobility::RichText::Content.new(html)

    # Should not raise, even with empty attachment
    assert_includes content.to_html, "<action-text-attachment"
  end

  def test_malformed_attachment_tag_preserved
    html = '<action-text-attachment sgid="incomplete"'
    content = Mobility::RichText::Content.new(html)

    # ActionText::Content handles this gracefully
    refute_nil content.to_html
  end

  def test_content_with_only_attachment
    content = Mobility::RichText::Content.new(SAMPLE_ATTACHMENT)

    refute content.blank?
    assert content.present?
  end
end
